'use strict';
const $=id=>document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d');
const W=1200,H=660;let state,tab='gear',auto=true,speed=1,muted=true,aim={x:850,y:410},held=false,last=0,clock=0,toastTimer,audio;
const names=['숲의 전조','울부짖는 무리','철갑의 행진','가시왕의 습격','얼어붙은 길','검은 날개','끝없는 행렬','서리 거인의 분노','붉은 달','몰려오는 어둠','최후의 공성','잿빛 군주'];
const items={gear:[{id:'bow',icon:'➶',name:'전쟁 장궁',desc:'공격력 +9',base:65},{id:'quiver',icon:'⋙',name:'질풍의 화살통',desc:'공격 속도 +15%',base:75},{id:'lens',icon:'◎',name:'매의 눈',desc:'치명타 확률 +7%',base:85}],skills:[{id:'meteor',icon:'☄',name:'유성우',desc:'모든 적에게 피해 · 22초 재사용',base:100},{id:'frost',icon:'❄',name:'서리 폭풍',desc:'전체 감속 + 피해 · 20초 재사용',base:90},{id:'heal',icon:'✚',name:'치유의 빛',desc:'성 내구도 회복 · 28초 재사용',base:90}],castle:[{id:'wall',icon:'♜',name:'성벽 보강',desc:'최대 내구도 +70, 내구도 +70',base:70},{id:'mine',icon:'◈',name:'왕실 금광',desc:'스테이지 보상 +30 G',base:85},{id:'repair',icon:'⚒',name:'성벽 수리',desc:'내구도 90 회복',base:55}]};
const blessings=[{id:'power',icon:'➶',name:'거인의 활시위',desc:'모든 화살의 공격력이 25% 증가합니다.'},{id:'multi',icon:'⋙',name:'갈라지는 화살',desc:'동시에 쏘는 화살이 1개 증가합니다. 최대 5개.'},{id:'pierce',icon:'◇',name:'관통의 룬',desc:'화살이 적을 1명 더 관통합니다.'},{id:'flame',icon:'♨',name:'잿불의 축복',desc:'화살에 맞은 적에게 3초간 화상 피해를 줍니다.'},{id:'frostbite',icon:'❄',name:'겨울의 숨결',desc:'화살에 맞은 적의 이동 속도를 35% 낮춥니다.'},{id:'wealth',icon:'◈',name:'황금의 서약',desc:'적 처치 골드가 30% 증가합니다.'},{id:'vamp',icon:'✚',name:'생명의 수확',desc:'적을 처치할 때 성 내구도를 3 회복합니다.'},{id:'haste',icon:'ϟ',name:'바람의 맹세',desc:'발사 속도가 20% 증가합니다.'},{id:'bastion',icon:'♜',name:'불멸의 성채',desc:'최대 내구도와 현재 내구도가 80 증가합니다.'}];
function fresh(){return{phase:'ready',stage:1,gold:120,hp:240,maxHp:240,kills:0,levels:{bow:0,quiver:0,lens:0,meteor:1,frost:0,heal:0,wall:0,mine:0,repair:0},relics:[],enemies:[],shots:[],particles:[],texts:[],effects:[],cd:[0,0,0],spawnLeft:0,spawnTimer:0,shootTimer:0,total:0,cleared:0,paused:false,time:0};}
function count(id){return state.relics.filter(v=>v===id).length;}
function stats(){return{damage:(24+state.levels.bow*9)*Math.pow(1.25,count('power')),rate:1.8*(1+state.levels.quiver*.15)*Math.pow(1.2,count('haste')),crit:Math.min(.65,.1+state.levels.lens*.07),multi:Math.min(5,1+count('multi'))};}
function notify(t){$('toast').textContent=t;$('toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.opacity=0,2400);}
function beep(freq=300,duration=.05){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function cost(it){return it.id==='repair'?55:Math.round(it.base*Math.pow(1.48,state.levels[it.id]-(it.id==='meteor'?1:0)));}
function renderShop(){const can=state.phase==='ready';$('shop').innerHTML=items[tab].map(it=>{let lv=state.levels[it.id],max=it.id!=='repair'&&lv>=6;return `<div class="item"><span class="item-icon">${it.icon}</span><div><b>${it.name}</b><em>${it.id==='repair'?'':lv?'LV.'+lv:'미보유'}</em><small>${it.desc}</small></div><button data-buy="${it.id}" ${!can||max||state.gold<cost(it)||(it.id==='repair'&&state.hp>=state.maxHp)?'disabled':''}>${max?'MAX':'◈ '+cost(it)}</button></div>`}).join('');$('shop').querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy));}
function buy(id){const it=Object.values(items).flat().find(x=>x.id===id);if(!it||state.phase!=='ready'||state.gold<cost(it)||(id!=='repair'&&state.levels[id]>=6))return false;if(id==='repair'&&state.hp>=state.maxHp)return false;state.gold-=cost(it);if(id==='repair')state.hp=Math.min(state.maxHp,state.hp+90);else{state.levels[id]++;if(id==='wall'){state.maxHp+=70;state.hp+=70;}}beep(600);render();return true;}
function render(){const s=stats();$('gold').textContent=state.gold;$('hpText').textContent=`${Math.ceil(state.hp)} / ${state.maxHp}`;$('hpBar').style.width=`${Math.max(0,state.hp/state.maxHp*100)}%`;$('hpBar').style.background=state.hp/state.maxHp<.3?'#d9806e':'#b4c08b';$('damage').textContent=Math.round(s.damage);$('rate').textContent=s.rate.toFixed(1);$('crit').textContent=Math.round(s.crit*100)+'%';$('arrows').textContent=s.multi-1;$('kills').textContent='처치 '+state.kills;$('phase').textContent=state.paused?'일시정지':({ready:'전투 준비',battle:'방어 중',reward:'밤을 넘겼습니다',lost:'성 함락',won:'원정 성공'})[state.phase];$('stage').textContent=`STAGE ${String(state.stage).padStart(2,'0')} / 12`;$('waveName').textContent=String(state.stage).padStart(2,'0')+' — '+names[state.stage-1];$('remaining').textContent=state.phase==='battle'?`남은 적 ${state.spawnLeft+state.enemies.length} / ${state.total}`:state.phase==='ready'?'장비를 준비하고 전투를 시작하세요':'전투 종료';$('shopStatus').textContent=state.phase==='ready'?'구매 가능':'전투 사이에 구매';$('income').textContent='추가 보상 +'+state.levels.mine*30+' G';$('relicCount').textContent=state.relics.length;$('relics').innerHTML=state.relics.length?[...new Set(state.relics)].map(id=>{let r=blessings.find(x=>x.id===id);return `<span class="relic" title="${r.desc}">${r.icon} ${r.name}${count(id)>1?' ×'+count(id):''}</span>`}).join(''):'밤을 넘길 때마다 새로운 힘을 얻습니다.';$('track').innerHTML=Array.from({length:12},(_,i)=>`<span class="${i+1===state.stage?'current ':i+1<state.stage?'done ':''}${(i+1)%4===0?'boss':''}">${i+1<state.stage?'✓':i+1}</span>`).join('');$('pause').textContent=state.paused?'▶':'Ⅱ';$('pause').disabled=state.phase!=='battle';renderShop();renderSkills();}
function renderSkills(){['meteor','frost','heal'].forEach((id,i)=>{let level=state.levels[id];$('cd'+i).textContent=!level?'상점에서 해금':state.cd[i]>0?Math.ceil(state.cd[i])+'초':'사용 가능 · Lv.'+level;$('cast'+i).disabled=state.phase!=='battle'||state.paused||!level||state.cd[i]>0;});}
function start(){if(state.phase!=='ready')return false;state.phase='battle';state.paused=false;state.spawnLeft=10+state.stage*3;state.total=state.spawnLeft;state.spawnTimer=.6;state.shootTimer=0;state.time=0;state.cd=[0,0,0];$('center').classList.add('hidden');render();return true;}
function spawn(){let index=state.total-state.spawnLeft;let type=state.stage%4===0&&state.spawnLeft===1?'boss':state.stage>=5&&index%6===3?'bat':state.stage>=3&&index%5===2?'tank':index%4===1?'runner':'grunt';let hp=type==='boss'?240+state.stage*80:(type==='tank'?75:type==='runner'?22:type==='bat'?30:35)*(1+state.stage*.16);let y=type==='bat'?260+Math.random()*100:350+Math.random()*210;state.enemies.push({x:W+30,y,hp,max:hp,type,speed:type==='boss'?20:type==='tank'?24:type==='runner'?62:type==='bat'?52:34,r:type==='boss'?35:type==='tank'?21:16,attack:0,slow:0,burn:0,burnDmg:0,flash:0,seed:Math.random()*20});state.spawnLeft--;}
function damage(e,n,crit=false){if(e.hp<=0)return;e.hp-=n;e.flash=.12;state.texts.push({x:e.x,y:e.y-e.r-14,text:Math.ceil(n)+(crit?'!':''),life:.6,color:crit?'#ffe09c':'#e4e8d2'});if(e.hp<=0){const gold=Math.round((e.type==='boss'?75:e.type==='tank'?15:9)*(1+.3*count('wealth')));state.gold+=gold;state.kills++;state.hp=Math.min(state.maxHp,state.hp+3*count('vamp'));state.texts.push({x:e.x,y:e.y-30,text:'+'+gold+' G',life:1,color:'#e6c075'});burst(e.x,e.y,e.type==='boss'?'#dba772':'#b0c7a5',12);beep(160,.04);}}
function burst(x,y,color,n){for(let i=0;i<n;i++)state.particles.push({x,y,vx:(Math.random()-.5)*160,vy:(Math.random()-.5)*150,life:.3+Math.random()*.5,color});}
function shoot(){let targets=state.enemies.filter(e=>e.hp>0);if(!targets.length)return;let target=auto?targets.reduce((a,b)=>a.x<b.x?a:b):aim;let sx=218,sy=320;let tx=target.x,ty=target.y;if(auto)tx-=target.speed*Math.hypot(tx-sx,ty-sy)/780;let angle=Math.atan2(ty-sy,tx-sx),s=stats();for(let k=0;k<s.multi;k++){let a=angle+(k-(s.multi-1)/2)*.085;state.shots.push({x:sx,y:sy,vx:Math.cos(a)*780,vy:Math.sin(a)*780,life:2,hit:new Set(),pierce:count('pierce'),damage:s.damage});}beep(450,.03);}
function cast(i){if(!Number.isInteger(i)||i<0||i>2)return false;let id=['meteor','frost','heal'][i],lv=state.levels[id];if(state.phase!=='battle'||state.paused||!lv||state.cd[i]>0)return false;state.cd[i]=[22,20,28][i];if(i===0){for(const e of state.enemies){damage(e,65+lv*40);burst(e.x,e.y,'#efaa65',18);}state.effects.push({kind:'meteor',life:.8});}if(i===1){for(const e of state.enemies){damage(e,15+lv*14);e.slow=4+lv;}state.effects.push({kind:'frost',life:1});}if(i===2){state.hp=Math.min(state.maxHp,state.hp+50+lv*35);state.effects.push({kind:'heal',life:1});}beep(i===2?700:90,.25);render();return true;}
function chooseReward(){state.phase='reward';state.cleared=state.stage;const bonus=45+state.stage*10+state.levels.mine*30;state.gold+=bonus;state.shots=[];saveBest();render();if(state.stage===12){finish(true);return;}const choices=blessings.filter(x=>x.id!=='multi'||count('multi')<4).sort(()=>Math.random()-.5).slice(0,3);$('dialogContent').innerHTML=`<span class="eyebrow">NIGHT ${String(state.stage).padStart(2,'0')} SURVIVED · +${bonus} G</span><h2>어둠을 넘긴 자의 보상</h2><p>축복 하나를 선택하세요. 이번 원정이 끝날 때까지 유지됩니다.</p><div class="choices">${choices.map(r=>`<button class="choice" data-reward="${r.id}"><span>${r.icon}</span><b>${r.name}</b><small>${r.desc}</small></button>`).join('')}</div>`;$('dialogContent').querySelectorAll('[data-reward]').forEach(b=>b.onclick=()=>{state.relics.push(b.dataset.reward);if(b.dataset.reward==='bastion'){state.maxHp+=80;state.hp+=80;}state.stage++;state.phase='ready';state.enemies=[];$('dialog').close();showReady();render();});$('dialog').showModal();}
function showReady(){$('center').innerHTML=`<span class="eyebrow">PREPARE FOR NIGHT ${String(state.stage).padStart(2,'0')}</span><h2>${state.stage%4===0?'보스가 다가옵니다.':'잠시, 활시위를 고르세요.'}</h2><p>${names[state.stage-1]} · 골드로 장비와 스킬을 강화하세요.</p><button id="start" class="primary">${state.stage}번째 밤 시작 <span>→</span></button><small>${state.stage%4===0?'체력이 높은 보스가 마지막에 출현합니다.':'상점에서 장비·스킬·성채를 선택할 수 있어요.'}</small>`;$('center').classList.remove('hidden');$('start').onclick=start;}
function saveBest(){try{const best=Math.max(Number(localStorage.getItem('bastion-best')||0),state.cleared);localStorage.setItem('bastion-best',String(best));$('best').textContent=best+' / 12';}catch{$('best').textContent=state.cleared+' / 12';}}
function finish(won){state.phase=won?'won':'lost';state.hp=Math.max(0,state.hp);saveBest();render();$('dialogContent').innerHTML=`<span class="eyebrow">${won?'THE DAWN IS YOURS':'THE LAST ARROW'}</span><h2>${won?'마침내, 새벽이 밝았습니다.':'성은 무너져도, 도전은 남습니다.'}</h2><p>${state.cleared}개 스테이지 방어 성공 · ${state.kills}마리 처치<br>획득한 축복 ${state.relics.length}개 · 남은 골드 ${state.gold} G<br>새 원정에서는 장비와 축복이 초기화됩니다. 최고 기록은 이 브라우저에 남습니다.</p><button id="restart" class="primary">새 원정 시작 →</button>`;$('restart').onclick=()=>{$('dialog').close();state=fresh();showReady();render();};$('dialog').showModal();}
function update(dt){if(state.phase!=='battle'||state.paused)return;state.time+=dt;state.cd=state.cd.map(c=>Math.max(0,c-dt));state.spawnTimer-=dt;if(state.spawnLeft>0&&state.spawnTimer<=0){spawn();state.spawnTimer=Math.max(.48,1.35-state.stage*.055);}state.shootTimer-=dt;if(state.shootTimer<=0&&(auto||held)){shoot();state.shootTimer=1/stats().rate;}
for(const e of state.enemies){if(e.hp<=0)continue;e.flash=Math.max(0,e.flash-dt);e.slow=Math.max(0,e.slow-dt);if(e.burn>0){e.burn-=dt;e.hp-=e.burnDmg*dt;if(e.hp<=0){e.hp=.01;damage(e,1);continue;}}if(e.x>250){e.x-=e.speed*(1+state.stage*.025)*(e.slow>0?.4:1)*dt;}else{e.attack-=dt;if(e.attack<=0){state.hp-=e.type==='boss'?24:e.type==='tank'?11:6;e.attack=1.3;burst(250,e.y,'#e9a27f',5);}}}
for(const a of state.shots){let px=a.x,py=a.y;a.x+=a.vx*dt;a.y+=a.vy*dt;a.life-=dt;for(const e of state.enemies){if(e.hp<=0||a.hit.has(e))continue;let dx=a.x-px,dy=a.y-py,t=Math.max(0,Math.min(1,((e.x-px)*dx+(e.y-py)*dy)/(dx*dx+dy*dy||1)));if(Math.hypot(e.x-(px+dx*t),e.y-(py+dy*t))<e.r+5){let critical=Math.random()<stats().crit;damage(e,a.damage*(critical?2:1)*(e.type==='tank'?.75:1),critical);a.hit.add(e);if(count('flame')){e.burn=3;e.burnDmg=8*count('flame');}if(count('frostbite'))e.slow=1.5;if(a.hit.size>a.pierce){a.life=0;break;}}}}
state.shots=state.shots.filter(a=>a.life>0&&a.x<W+50&&a.y>-50&&a.y<H+50);state.enemies=state.enemies.filter(e=>e.hp>0);if(state.hp<=0){finish(false);return;}if(!state.spawnLeft&&!state.enemies.length)chooseReward();}
// The battlefield and moving actors are rendered directly by the Canvas game engine.
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fill();}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h);}
function ellipse(x,y,rx,ry,c){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function tree(x,y,s,c){rect(x-4*s,y-8*s,8*s,50*s,'#202f2a');for(let i=0;i<3;i++)poly([[x,y-(100-i*25)*s],[x-(35+i*8)*s,y+i*8*s],[x+(35+i*8)*s,y+i*8*s]],c);}
function background(){let grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#142830');grad.addColorStop(.57,'#415653');grad.addColorStop(1,'#2e3d30');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ellipse(930,110,43,43,'#c7ccab');ellipse(944,100,42,42,'#243a3e');poly([[0,230],[100,170],[200,225],[320,120],[510,255],[675,160],[820,245],[1020,150],[1200,225],[1200,430],[0,430]],'#263d40');poly([[0,300],[130,235],[290,292],[410,205],[620,314],[780,220],[960,295],[1110,215],[1200,260],[1200,460],[0,460]],'#304749');for(let i=0;i<29;i++)tree(i*47,300+Math.sin(i*2)*16,.6+((i*7)%5)*.08,'#273f3b');poly([[0,400],[210,354],[500,379],[800,349],[1200,362],[1200,660],[0,660]],'#374b3c');poly([[250,433],[490,414],[720,437],[980,406],[1200,425],[1200,565],[980,519],[770,548],[540,499],[250,527]],'#60634b');poly([[250,460],[570,444],[830,470],[1200,449],[1200,504],[880,502],[580,475],[250,500]],'#6a6b51');for(let i=0;i<90;i++){let x=(i*139+44)%1200,y=385+(i*97)%275;ellipse(x,y,2+(i%3),1,'#77826855');}for(let i=0;i<11;i++)tree(365+i*90,328+Math.sin(i*3)*18,.6+(i%3)*.12,'#233d32');for(let i=0;i<9;i++)tree(340+i*113,640+(i%3)*20,.9+(i%2)*.3,'#20392e');ellipse(157,559,170,43,'#13231b70');
// Castle geometry is collision-aligned with the defense line.
rect(55,260,156,282,'#59635a');poly([[55,260],[90,236],[238,248],[211,273]],'#7c8270');rect(211,271,37,273,'#424f46');rect(42,290,188,27,'#828775');for(let i=0;i<6;i++)rect(42+i*34,271,22,26,'#858975');rect(76,213,77,109,'#626d60');rect(67,204,95,21,'#92947c');for(let i=0;i<3;i++)rect(67+i*34,186,23,24,'#90937b');poly([[70,187],[115,142],[160,187]],'#46594b');rect(111,112,4,43,'#a8a887');poly([[115,112],[155,119],[144,137],[115,132]],'#b09358');for(let row=0;row<9;row++)for(let col=0;col<4;col++){let x=57+col*39+(row%2)*-16;rect(x,331+row*22,34,1,'#8d947455');}rect(103,440,60,103,'#23312b');ellipse(133,440,30,31,'#23312b');rect(108,445,50,98,'#3b382a');for(let i=0;i<5;i++)rect(110+i*10,443,2,100,'#5f5b3d');rect(102,475,61,5,'#1c2822');rect(102,512,61,5,'#1c2822');rect(97,243,16,30,'#202f2b');rect(175,350,18,36,'#27372e');rect(63,405,9,51,'#342c21');ellipse(68,398,7+Math.sin(clock*9)*2,15,'#ddab64');ellipse(68,397,3,9,'#f8db91');rect(208,410,7,48,'#342c21');ellipse(211,402,7+Math.sin(clock*8)*2,14,'#ddab64');
// Archer on the rampart.
let angle=Math.atan2(aim.y-320,aim.x-218);if(auto&&state.enemies.length){let e=state.enemies.reduce((a,b)=>a.x<b.x?a:b);angle=Math.atan2(e.y-320,e.x-218);}ellipse(210,339,14,5,'#25352a');rect(200,312,13,22,'#c1bc96');poly([[201,312],[194,342],[212,334]],'#839775');ellipse(207,305,7,8,'#d4c09b');poly([[199,302],[206,292],[216,306]],'#526d52');ctx.save();ctx.translate(211,319);ctx.rotate(angle);ctx.strokeStyle='#c6a66c';ctx.lineWidth=3;ctx.beginPath();ctx.arc(7,0,18,-1.15,1.15);ctx.stroke();ctx.strokeStyle='#d9d6b6';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(14,-16);ctx.lineTo(14,16);ctx.stroke();rect(-1,-2,17,4,'#c7bc98');ctx.restore();}
function enemy(e){let bob=Math.sin(clock*9+e.seed)*2,s=e.type==='boss'?2:e.type==='tank'?1.3:1,x=e.x,y=e.y;ctx.save();ctx.translate(x,y);ctx.scale(s,s);ellipse(0,17,14,4,'#14251b66');if(e.type==='bat'){let f=Math.sin(clock*14)*12;poly([[-3,0],[-30,-15-f],[-21,7],[-7,10]],'#7f91a1');poly([[3,0],[30,-15-f],[21,7],[7,10]],'#7f91a1');ellipse(0,0,8,11,'#627384');rect(-6,-3,3,3,'#e9be7b');rect(3,-3,3,3,'#e9be7b');}else{let color=e.flash>0?'#f1dfb5':e.type==='boss'?'#765c52':e.type==='tank'?'#77827c':e.type==='runner'?'#9a775b':'#7e9470';rect(-8,2+bob,6,17-bob,'#333e30');rect(3,2-bob,6,17+bob,'#333e30');poly([[-12,-8+bob],[8,-8+bob],[13,8],[-13,8]],color);ellipse(-2,-16+bob,9,9,color);poly([[-10,-18+bob],[-18,-21+bob],[-10,-11+bob]],color);rect(-8,-17+bob,4,2,'#e8c27a');ctx.strokeStyle='#c4c0a0';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-15,1);ctx.lineTo(-28,-20);ctx.stroke();if(e.type==='tank'){ellipse(-13,-1,8,14,'#4a5b58');rect(-15,-10,3,20,'#b4b09b');}if(e.type==='boss'){poly([[-12,-21],[-15,-36],[-6,-29],[0,-40],[6,-28],[12,-35],[10,-20]],'#c8a56b');rect(12,-9,7,28,'#b19472');}}if(e.slow>0){ctx.strokeStyle='#9adddc';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.stroke();}if(e.burn>0)ellipse(9,-9,4,8,'#eea35e');ctx.restore();if(e.hp<e.max||e.type==='boss'){rect(x-e.r,y-e.r-16,e.r*2,4,'#17261d');rect(x-e.r,y-e.r-16,e.r*2*Math.max(0,e.hp/e.max),4,e.type==='boss'?'#d99878':'#b2bd86');}if(e.type==='boss'){ctx.fillStyle='#e5c499';ctx.font='13px sans-serif';ctx.textAlign='center';ctx.fillText(names[state.stage-1],x,y-e.r-26);}}
function draw(dt){background();state.enemies.slice().sort((a,b)=>a.y-b.y).forEach(enemy);for(const a of state.shots){ctx.save();ctx.translate(a.x,a.y);ctx.rotate(Math.atan2(a.vy,a.vx));rect(-24,-1,27,2,count('flame')?'#efad66':'#e1d7a4');poly([[4,0],[-3,-4],[-3,4]],'#e3dcb8');ctx.restore();}const moving=state.phase!=='battle'||!state.paused;for(const p of state.particles){if(moving){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}ctx.globalAlpha=Math.max(0,p.life);rect(p.x,p.y,3,3,p.color);}ctx.globalAlpha=1;state.particles=state.particles.filter(p=>p.life>0);for(const t of state.texts){if(moving){t.y-=dt*30;t.life-=dt;}ctx.globalAlpha=Math.min(1,Math.max(0,t.life*2));ctx.fillStyle=t.color;ctx.font='bold 15px sans-serif';ctx.textAlign='center';ctx.fillText(t.text,t.x,t.y);}ctx.globalAlpha=1;state.texts=state.texts.filter(t=>t.life>0);for(const f of state.effects){if(moving)f.life-=dt;if(f.kind==='meteor'){for(let i=0;i<9;i++){let x=330+i*110,y=80+(1-f.life)*480;ctx.strokeStyle='#ffc384';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x+60,y-100);ctx.lineTo(x,y);ctx.stroke();ellipse(x,y,7,10,'#f5b06e');}}else{ctx.globalAlpha=Math.max(0,f.life*.22);rect(0,0,W,H,f.kind==='frost'?'#b5edff':'#c6ee90');ctx.globalAlpha=1;}}state.effects=state.effects.filter(f=>f.life>0);if(!auto&&state.phase==='battle'){ctx.strokeStyle='#e6cc8c';ctx.lineWidth=1;ctx.beginPath();ctx.arc(aim.x,aim.y,11,0,Math.PI*2);ctx.moveTo(aim.x-17,aim.y);ctx.lineTo(aim.x+17,aim.y);ctx.moveTo(aim.x,aim.y-17);ctx.lineTo(aim.x,aim.y+17);ctx.stroke();}if(state.paused){rect(0,0,W,H,'#07151088');ctx.textAlign='center';ctx.fillStyle='#e7dec2';ctx.font='26px sans-serif';ctx.fillText('일시정지',W/2,H/2);ctx.font='14px sans-serif';ctx.fillText('SPACE 또는 ▶ 버튼으로 계속',W/2,H/2+32);}}
let uiTimer=0;function frame(time){const real=Math.min((time-last)/1000||0,.05);last=time;const dt=real*speed;if(!state.paused)clock+=dt;update(dt);draw(dt);uiTimer+=real;if(uiTimer>.12){renderSkills();$('gold').textContent=state.gold;$('hpText').textContent=Math.ceil(Math.max(0,state.hp))+' / '+state.maxHp;$('hpBar').style.width=Math.max(0,state.hp/state.maxHp*100)+'%';$('kills').textContent='처치 '+state.kills;if(state.phase==='battle')$('remaining').textContent=`남은 적 ${state.spawnLeft+state.enemies.length} / ${state.total}`;uiTimer=0;}requestAnimationFrame(frame);}
function togglePause(){if(state.phase!=='battle')return;state.paused=!state.paused;held=false;render();}
function pointer(e){const r=canvas.getBoundingClientRect();aim={x:Math.max(255,(e.clientX-r.left)/r.width*W),y:(e.clientY-r.top)/r.height*H};}
canvas.onpointermove=pointer;canvas.onpointerdown=e=>{pointer(e);held=true;canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=()=>held=false;canvas.onpointercancel=()=>held=false;$('auto').onclick=()=>{auto=!auto;$('auto').textContent='자동 조준 '+(auto?'ON':'OFF');$('auto').classList.toggle('active',auto);notify(auto?'가장 가까운 적을 자동으로 공격합니다.':'전장을 누르고 있으면 조준 방향으로 연사합니다.');};$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=speed+'×';};$('pause').onclick=togglePause;$('sound').onclick=()=>{muted=!muted;$('sound').textContent='소리 '+(muted?'꺼짐':'켜짐');beep(600);};$('start').onclick=start;[0,1,2].forEach(i=>$('cast'+i).onclick=()=>cast(i));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('selected',el===b));renderShop();});
$('help').onclick=()=>{if($('dialog').open)return;let resume=state.phase==='battle'&&!state.paused;if(resume)togglePause();$('dialogContent').innerHTML='<span class="eyebrow">FIELD MANUAL</span><h2>최후의 성, 방어 지침</h2><p>• 자동 조준 ON: 가장 가까운 적을 자동으로 공격합니다.<br>• 자동 조준 OFF: 마우스 또는 터치로 전장을 누르면 연사합니다.<br>• Q 유성우: 전체 피해 / W 서리 폭풍: 전체 감속 / E 치유의 빛: 성 회복<br>• SPACE: 일시정지 / 1× 버튼: 전투 속도 변경<br>• 적을 처치하면 골드가 즉시 지급됩니다. 전투 사이에 상점에서 강화하세요.<br>• 매 스테이지 종료 후 무작위 축복 3개 중 1개를 선택합니다.<br>• 4 · 8 · 12 스테이지에는 보스가 등장합니다. 12단계를 지키면 승리합니다.<br>• 성이 무너지면 원정이 종료됩니다. 최고 기록만 이 브라우저에 저장됩니다.</p><button id="closeHelp" class="primary">알겠습니다</button>';$('dialog').showModal();$('closeHelp').onclick=()=>{$('dialog').close();if(resume)togglePause();};};$('dialog').addEventListener('cancel',e=>{e.preventDefault();if($('closeHelp'))$('closeHelp').click();});window.addEventListener('keydown',e=>{if(e.repeat||$('dialog').open||e.target.closest('input'))return;if(e.code==='Space'){e.preventDefault();togglePause();}let i=['KeyQ','KeyW','KeyE'].indexOf(e.code);if(i>=0)cast(i);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.phase==='battle'&&!state.paused)togglePause();});
state=fresh();try{$('best').textContent=(Number(localStorage.getItem('bastion-best'))||0)+' / 12';}catch{$('best').textContent='0 / 12';}render();requestAnimationFrame(frame);
if(document.modelContext?.registerTool){const life=new AbortController();for(const tool of [{name:'read_expedition',description:'Read the current local game stage, castle health, gold and upgrades.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({stage:state.stage,phase:state.phase,gold:state.gold,hp:state.hp,levels:{...state.levels}})},{name:'start_night',description:'Start the next defense battle from the preparation phase.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>({started:start(),phase:state.phase})}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
